# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ff4798f9453cf9fe56b9facbca8702b30f3fa7259923c94774c9b08c7286a312504848ad8b4d6ac702800b6afe5de012c3d05efe47078672754efa8c8c9ffd6

test:
  secret_key_base: cf8d885f6688daffbf57968420ec09b87adef45556f66bf05cd8a340e87be5c54f6580ec9f4c543c98a799fae30a50058763132010bdc9c283a5b8b07157b61e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
